### ISSUE TITLE
Inlay hints' color theme don't look good after VSCode April 2022 (1.67) update

### ISSUE THREAD

**Issue by lynzrand** [troydraws/paddy-color-theme#12]
VSCode April 2022 introduced the "compact" style of inlay hints as default (https://github.com/microsoft/vscode/pull/145470), which removes paddings and rounded corners and set the font size the same as editor. In this style, inlay hints should look like comments to look good and "blend in".

Inlay hints in most of the Paddy themes have an inverted color scheme and/or low contrast, which doesn't look good.

![图片](https://user-images.githubusercontent.com/10259119/172052449-c193b3d4-f19a-47b6-957d-e7aa2781238d.png)

![图片](https://user-images.githubusercontent.com/10259119/172052461-a1361802-d0f9-426b-98a8-eef02b63bb83.png)

![图片](https://user-images.githubusercontent.com/10259119/172052797-a63bc164-2ebf-4359-8ed9-d34dddace7d4.png)

Some themes in Paddy do have a better inlay hint color scheme, e.g. P. Machine:

![图片](https://user-images.githubusercontent.com/10259119/172052436-b654702e-0cc6-4237-9253-b9e0a40f1ce7.png)

# List of themes with not-so-nice-looking inlay hints

Themes with inverted color scheme:

- Dark themes
	  - Black
	  - Citadel
	  - Emerald
	  - Eucalyptus
	  - Floresta
	  - Grizzly
	  - Haze
	  - Inkstone
	  - Leipzig
	  - Ornithopter
	  - Ox
	  - Wolf
	  - Yesterday
- Light themes	  
	  - Crimson
	  - Frost
	  - Genmaicha
	  - Light

Themes with too low contrast:

- Dark themes
	  - Inkstone
	  - Ornithopter
	  - Wolf
	  - Yesterday 
- Light themes	  
	  - Crimson
	  - Frost
	  - Genmaicha
	  - Light

**Comment by yl92** [comment]
Thanks for reporting! I haven't used this feature before so never noticed this. Will take a look soon!

**Comment by lynzrand** [comment]
Yay the new inlay hints colors look great! Thanks!
