### ISSUE TITLE
Incorrect syntax highlighting for Queue in Java

### ISSUE THREAD

**Issue by w0lvram** [troydraws/paddy-color-theme#20]
Queue type has incorrect syntax highlighting (should have the same color as ArrayList and String in attached screenshot)

<img width="510" alt="Screenshot 2023-08-19 at 20 32 30" src="https://github.com/yl92/paddy-color-theme/assets/42044611/4c227063-c717-4acf-adad-6cbb8abf6475">

**Comment by yl92** [comment]
Hey! When I added this code snippet to my VSCode it appears to highlight the syntax correctly. 
<img width="487" alt="image" src="https://github.com/yl92/paddy-color-theme/assets/13817751/72fd2528-b309-4cbb-b14d-a3ee96d1e5d1">
