### ISSUE TITLE
Duplicated underline in hint/info squiggles

### ISSUE THREAD

**Issue by lynzrand** [troydraws/paddy-color-theme#3]
Hint level squiggles:

![图片](https://user-images.githubusercontent.com/10259119/114695062-c3537000-9d4d-11eb-863b-8a22632867fc.png)

Info level squiggles

![图片](https://user-images.githubusercontent.com/10259119/114695100-cf3f3200-9d4d-11eb-9310-83a0939b122d.png)

I checked this with multiple plugins and environments (and disabled all other plugins), so this issue is probably not created by some other random plugin.

**Comment by yl92** [comment]
Hi there! This looks like rust? I've tried to put the content into the editor just now and the hints didn't show up. Is there some settings I need to turn on for the hints to show? (I don't use rust myself)

**Comment by lynzrand** [comment]
These aren't default behaviors, I'm just using [Rust Analyzer](https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer) and its custom settings as a way to trigger info/hint squiggles.

In theory, any info or hint level squiggles should work (I first observed this issue when using [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)), so you may try emitting squiggles using your preferred plugins.

Here are example of ones triggered by Spell Checker (use `cSpell.diagnosticLevel` to change level):

![图片](https://user-images.githubusercontent.com/10259119/114712667-edfbf380-9d62-11eb-9ef1-298d3bc437a3.png)

![图片](https://user-images.githubusercontent.com/10259119/114712662-eb999980-9d62-11eb-9316-e449aa0fee5d.png)

**Comment by yl92** [comment]
Thank you! I can see the behaviour now, will look into it soon and revert back.

**Comment by yl92** [comment]
Howdy @lynzrand! You should be able to update the theme now for the patch :)

**Comment by lynzrand** [comment]
Yay it's working! Thanks!

BTW, what's that border that appeared under the squiggle?

**Comment by yl92** [comment]
Thanks for reporting the bug too! I'd never have realised the issue since I never saw them. Instead of using `"editorHint.foreground"` I accidentally used `"editorHint.border"`, which is the double underline style intended for high contrast themes, so it renders the 'foreground' (the default squiggly line) and the double border at the same time. You can switch to a high contrast theme to see those double borders on their own.

**Comment by lynzrand** [comment]
Got that!
