### ISSUE TITLE
"Bright black" color in terminal is too dark in Machine / Mist theme

### ISSUE THREAD

**Issue by lynzrand** [troydraws/paddy-color-theme#4]
The following screenshots should explain the problem.

![图片](https://user-images.githubusercontent.com/10259119/120895345-13182e80-c64f-11eb-96cf-bcb4c1f238cf.png)

^ P. Machine

![图片](https://user-images.githubusercontent.com/10259119/120895398-5d011480-c64f-11eb-97d8-92fcd9713f3c.png)

^ P. Mist

## Expected behavior

![图片](https://user-images.githubusercontent.com/10259119/120895451-84f07800-c64f-11eb-984c-cd3a6b02d6bb.png)

"Bright black" should be brighter than the terminal background. The screenshot above is captured with P. Citadel theme.

**Comment by yl92** [comment]
Thanks for submitting this @lynzrand, the black does look a bit odd that way. I'll take a look at this before publishing the next version.

**Comment by lynzrand** [comment]
Here's another problem in coloring, though it's not worth a separate issue:

![图片](https://user-images.githubusercontent.com/10259119/120932456-66aa7b00-c728-11eb-8c39-935438e35bf1.png)

^ Token highlight (that one when you put your cursor above one word) is too bright in P. Citadel theme.

**Comment by yl92** [comment]
@lynzrand Howdy - A new version is just up, addressed above issues and comes with three new summery themes too. Should be visible in the store in a few minutes. Take a look and see what you think!

**Comment by lynzrand** [comment]
I can confirm the above issues are solved, and the new themes looks very nice! (Though I'll continue to stay on P.Citadel/P.Machine for now.) Thanks again for providing such a pleasing theme for us!

**Comment by yl92** [comment]
You are more than welcome, glad you like them!
