### ISSUE TITLE
wrong color in search input

### ISSUE THREAD

**Issue by nicholasxjy** [troydraws/paddy-color-theme#5]
<img width="1300" alt="Screen Shot 2021-06-23 at 1 44 42 PM" src="https://user-images.githubusercontent.com/3580943/123042641-b4fa9200-d429-11eb-82ea-b055eba7edc4.png">
 

<img width="1311" alt="Screen Shot 2021-06-23 at 1 44 54 PM" src="https://user-images.githubusercontent.com/3580943/123042582-a0b69500-d429-11eb-8c94-1580c79c99a3.png">

**Comment by yl92** [comment]
hiya, thanks for the report! looks like that the text is invisible for you when the input is focused? 
I'm not seeing this behaviour here on both macOS & Windows, can you let me know which version your OS and VS Code is? Does this happen with other themes too?

**Comment by nicholasxjy** [comment]
> hiya, thanks for the report! looks like that the text is invisible for you when the input is focused?
> I'm not seeing this behaviour here on both macOS & Windows, can you let me know which version your OS and VS Code is? Does this happen with other themes too?

It looks all good after updating VSCode insiders version. It should be VSCode insiders bug. Btw paddy is such a great theme
